name: ci
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: pip install mkdocs
      - run: pip install mkdocs-material
      - run: pip install mkdocs-material-extensions
      - run: pip install mkdocs-git-revision-date-localized-plugin
      - run: pip install mkdocs-add-number-plugin
      - run: pip install mkdocs-exclude
      - run: pip install mkdocs-minify-plugin
      - run: pip install mkdocs-redirects
      - run: mkdocs gh-deploy --force
